# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-21 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SoftballProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=50, unique=True)),
                ('school', models.CharField(max_length=50)),
                ('nickname', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=25)),
                ('field', models.CharField(max_length=50)),
                ('head_coach', models.CharField(max_length=50)),
                ('conference', models.CharField(max_length=25)),
                ('work_series_appearances', models.CharField(max_length=20)),
                ('titles', models.CharField(max_length=20)),
            ],
            options={
                'managed': False,
            },
        ),
    ]
